apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-ilab04 
  description: Secure Supply Chain Example for Simple setup of instructlab   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=test-ilab04  
    janus-idp.io/tekton: test-ilab04 
    backstage.io/kubernetes-id: test-ilab04 
    backstage.io/techdocs-ref: dir:. 
    quay.io/repository-slug: tpetkos/ilab-test04
  tags: ["ai", "instructlab", "python", "terminado"] 
spec:
  type: service
  owner: user:guest 
  lifecycle: experimental
 